### ISSUE TITLE
New docker image monica:2.19.1-apache

### ISSUE THREAD

**Issue by peetersdaan** [Underpath/Monica_on_Synology#1]
@Underpath, Thanks for creating the guide!

The guide points however to monicahq/monicahq:latest as opposed to the latest image monica:2.19.1-apache.

Could you include the latest image in the guide or possibly update the guide to work with the latest image?

**Comment by Underpath** [comment]
Thanks so much for the feedback! You're right, at some point I updated my instance but completely forgot to update the guide; will do that at some point this week.

**Comment by peetersdaan** [comment]
Great! Perhaps you could show how to set it up with docker (as opposed to the packaged centre)?

In addition, 2.19.1 is already deprecated and the new version is 2.20.0.

**Comment by Underpath** [comment]
Just ran the upgrade myself and it worked just by using the latest image. I've made changes to the relevant files in the repo.

**Comment by peetersdaan** [comment]
Great, thanks for the support!

**Comment by emo1509** [comment]
Thanks for your guide. I followed all your steps and use the .json file in your example to create the container.  I notice that the location of the folders are different than the one I put in my .json file (see attached).
[monica_erik.zip](https://github.com/Underpath/Monica_on_Synology/files/6590568/monica_erik.zip)
When I look in the container, my files are at the following location ?
![2021-06-03_113535](https://user-images.githubusercontent.com/37776646/120623375-f79b0100-c45f-11eb-8e21-fe14ad3495dc.png)

I'm able to sent a test-mail, but he don't sent me notifications or reminders.

You have any idea what I'm doing wrong ?

Thanks in advance for your feedback.

**Comment by Underpath** [comment]
@emo1509 can you please open a new issue? I can look into this over the weekend.
